# Generated by Django 4.2.2 on 2023-09-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Book',
        ),
    ]
