# Generated by Django 4.2.2 on 2023-09-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_rename_library_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pirce',
            new_name='price',
        ),
    ]
